name: marvel_catalog
description: Catálogo de personagens Marvel
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  crypto: ^3.0.2  # lib de criptografia para geração do HASH da API
  result_dart: ^1.0.5
  envied: ^0.3.0  # lib para uso seguro das chaves no arquivo .env
  envied_generator: ^0.3.0
  equatable: ^2.0.5 # lib adicionada para simplificar a comparação de objetos
  flutter_bloc: ^8.1.2
  freezed: ^2.3.2
  get_it: ^7.2.0 # injeção de dependências
  http: ^0.13.5
  infinite_scroll_pagination: ^3.2.0
  injectable: ^2.1.1 #injeção de dependências
  mocktail: ^0.3.0 # mock de classes para fins de testes unitários
  path: any
  shimmer: ^2.0.0


dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/

